### ISSUE TITLE
Edit Project | Create Sample: Target object must not be null

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1602] opened 2018-08-14 12:15 UTC
I have updated to `v0.2.134` without any issues. Colleagues have created samples **after** this update in the morning, e.g.
```
Colleague's name | Sample created. | 2018-08-14 09:48:15
```
Now creating a sample this way results in an error:
```
Target object must not be null

org.springframework.util.Assert.notNull(Assert.java:115)
org.springframework.beans.AbstractNestablePropertyAccessor.setWrappedInstance(AbstractNestablePropertyAccessor.java:205)
org.springframework.beans.BeanWrapperImpl.setWrappedInstance(BeanWrapperImpl.java:151)
org.springframework.beans.AbstractNestablePropertyAccessor.setWrappedInstance(AbstractNestablePropertyAccessor.java:194)
org.springframework.beans.AbstractNestablePropertyAccessor.(AbstractNestablePropertyAccessor.java:133)
org.springframework.beans.BeanWrapperImpl.(BeanWrapperImpl.java:101)
org.springframework.beans.PropertyAccessorFactory.forBeanPropertyAccess(PropertyAccessorFactory.java:37)
org.springframework.web.servlet.tags.form.OptionWriter.doRenderFromCollection(OptionWriter.java:199)
org.springframework.web.servlet.tags.form.OptionWriter.renderFromCollection(OptionWriter.java:180)
org.springframework.web.servlet.tags.form.OptionWriter.writeOptions(OptionWriter.java:133)
org.springframework.web.servlet.tags.form.SelectTag.writeTagContent(SelectTag.java:218)
org.springframework.web.servlet.tags.form.AbstractFormTag.doStartTagInternal(AbstractFormTag.java:84)
org.springframework.web.servlet.tags.RequestContextAwareTag.doStartTag(RequestContextAwareTag.java:80)
org.apache.jsp.pages.editSample_jsp._jspx_meth_form_005fselect_005f1(editSample_jsp.java:4389)
org.apache.jsp.pages.editSample_jsp._jspService(editSample_jsp.java:739)
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1271)
org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1230)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
uk.ac.bbsrc.tgac.miso.webapp.context.ExposeRequestUrlFilter.doFilter(ExposeRequestUrlFilter.java:94)
org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
uk.ac.bbsrc.tgac.miso.webapp.context.PrometheusCollectionFilter.doFilter(PrometheusCollectionFilter.java:43)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.lang.Thread.run(Thread.java:748)
```
Going via Samples|Create results in the same error...

Any idea what is going wrong here?

**Comment by sklages** [comment] 2018-08-14 12:27
`miso_debug.log` states:
```
[...] 
# after update 
2018-08-14 07:09:53 INFO: Directory (/project/miso/current/storage/files/run/537) exists.
2018-08-14 07:29:08 INFO: Set context provider base url to: http://OUR.MISO.INSTANCE/miso
2018-08-14 07:29:20 INFO: Found role ROLE_EXTERNAL for klages
2018-08-14 07:29:20 INFO: Found role ROLE_INTERNAL for klages
2018-08-14 07:29:20 INFO: Found role ROLE_ADMIN for klages
2018-08-14 08:50:31 INFO: Set context provider base url to: http://OUR.MISO.INSTANCE/miso

# samples created
2018-08-14 08:50:41 INFO: Found role ROLE_INTERNAL for MY_COLLEAGUE
2018-08-14 08:50:41 INFO: Found role ROLE_ADMIN for MY_COLLEAGUE
2018-08-14 08:51:08 ERROR: Sample alias not valid: _#14206_K27ac_WT_L
2018-08-14 08:51:08 ERROR: Sample alias not valid: _#14207_K27ac_ZRSreg_L
2018-08-14 08:51:22 INFO: Sample alias OK!
2018-08-14 08:51:42 INFO: Sample alias OK!
2018-08-14 09:46:17 ERROR: Sample alias not valid: _#14209_ATAC_Lprom_2
2018-08-14 09:46:17 ERROR: Sample alias not valid: _#14208_ATAC_Lprom_1
2018-08-14 09:46:33 INFO: Sample alias OK!
2018-08-14 09:46:46 INFO: Sample alias OK!
2018-08-14 10:10:21 INFO: Set context provider base url to: http://OUR.MISO.INSTANCE/miso
2018-08-14 10:15:30 INFO: Found role ROLE_INTERNAL for ANOTHER_COLLEAGUE
2018-08-14 10:15:30 INFO: Found role ROLE_ADMIN for ANOTHER_COLLEAGUE
2018-08-14 10:15:30 INFO: Set context provider base url to: http://OUR.MISO.INSTANCE/miso
2018-08-14 13:31:08 INFO: Set context provider base url to: http://OUR.MISO.INSTANCE/miso
2018-08-14 13:31:13 INFO: Found role ROLE_INTERNAL for MY_COLLEAGUE
2018-08-14 13:31:13 INFO: Found role ROLE_ADMIN for MY_COLLEAGUE

# now error?
2018-08-14 13:53:40 ERROR: Target object must not be null
java.lang.IllegalArgumentException: Target object must not be null
    at org.springframework.util.Assert.notNull(Assert.java:115)
    at org.springframework.beans.AbstractNestablePropertyAccessor.setWrappedInstance(AbstractNestablePropertyAccessor.java:205)
    at org.springframework.beans.BeanWrapperImpl.setWrappedInstance(BeanWrapperImpl.java:151)
    at org.springframework.beans.AbstractNestablePropertyAccessor.setWrappedInstance(AbstractNestablePropertyAccessor.java:194)
    at org.springframework.beans.AbstractNestablePropertyAccessor.<init>(AbstractNestablePropertyAccessor.java:133)
    at org.springframework.beans.BeanWrapperImpl.<init>(BeanWrapperImpl.java:101)
[...]
```
The error shows up after confirming dialog `Create Samples|Quantity:1`.

hth

**Comment by djcooke** [comment] 2018-08-14 13:33
Thanks for reporting this.

Do you know how your colleagues were able to create samples? Is anyone else experiencing the issue if they perform the same steps as you?

**Comment by djcooke** [comment] 2018-08-14 13:41
Oh, I was able to reproduce this now. It happens on the *single* create sample page (`.../miso/sample/new`). I didn't think this page was still used, and in detailed sample mode it isn't. When creating a single sample in plain sample mode, you do get the `sample/new` page though. Your colleagues were likely able to create samples because they were creating multiple at once, and so they got the bulk page, which works fine.

I'll work on a fix for the `sample/new` page

**Comment by djcooke** [comment] 2018-08-14 15:31
Fixed in https://github.com/TGAC/miso-lims/pull/1604

This should be in release 0.2.136. You may want to roll back to the previous version that you had working until then. Otherwise, you can create single samples on the bulk page using the URL: `.../miso/sample/bulk/new?quantity=1`

I added a note about this bug to the release notes for the last few versions.

**Closed by djcooke** 2018-08-14 15:31 UTC
